#.travis.yml

language: node_js
node_js:
  - "5.11"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g angular-cli
  - npm install angular2-cookie --save
  - npm install bootstrap@next
  - npm install primeng --save
  - npm install font-awesome --save

script:
  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change